steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args:
        - build
        - -t
        - gcr.io/${PROJECT_ID}/$_SERVICE_NAME
        - .
      timeout: 1000s
    # Push the container image to Google Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args:
        - push
        - gcr.io/${PROJECT_ID}/$_SERVICE_NAME
      timeout: "1000s"
    # Deploy image to Cloud run
    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: gcloud
      args:
        - beta
        - run
        - jobs
        - update
        - $_SERVICE_NAME
        - --image
        - gcr.io/${PROJECT_ID}/$_SERVICE_NAME
        - --tasks
        - $_TASKS
        - --region
        - us-east1
        - --max-retries
        - '2'
        - --memory
        - '2Gi'
        - --cpu
        - '1'
        - --set-env-vars=SLEEP_MS=10000,SERVICE_NAME=$_SERVICE_NAME,TASK_OFFSET=$_TASK_OFFSET
        - --task-timeout
        - '3600s'


timeout: 2000s

images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME"