SHELL := /bin/bash

create_environment:
	python3.9 -m venv env-cloud-jobs

delete_environment:
	rm -rf env-mdoc-data-analysis

install:
	pip install --upgrade pip
	pip install -r requirements.lock.txt
